<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>application.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="application.manifest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Diagnostics.EventLog" Version="10.0.0" />
    <PackageReference Include="System.Threading.AccessControl" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="application.manifest" />
  </ItemGroup>

</Project>
